version: "3.7"

networks:
  network:
    name: ${PROJECT_NAME}

services:
  app:
    container_name: ${PROJECT_NAME}_front
    image: gitea/gitea:latest
    ports:
      - ${FRONT_HTTP_PORT}:3000
      - ${FRONT_SSH_PORT}:22
    volumes:
      - ./docker/front:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=db:${DB_PORT}
      - DB_NAME=${PROJECT_NAME}
      - DB_USER=root
      - DB_PASSWD=${DB_ROOT_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - network

  db:
    container_name: ${PROJECT_NAME}_db
    image: mariadb:latest
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    networks:
      - network
