version: "3.7"

networks:
  network:
    name: ${PROJECT_NAME}

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    # volumes:
    #   - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    command: -p ${DB_PORT}
    restart: always
    networks:
      - network

  front:
    container_name: ${PROJECT_NAME}_front
    image: gitea/gitea:latest
    ports:
      - ${FRONT_HTTP_PORT}:3000
      - ${FRONT_SSH_PORT}:22
    # volumes:
    #   - ./docker/front:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:${DB_PORT}
      - DB_NAME=${PROJECT_NAME}
      - DB_USER=${PROJECT_NAME}
      - DB_PASSWD=${DB_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - network
