version: "3.7"

networks:
  network:
    name: ${PROJECT_NAME}

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    # volumes:
    #   - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    command: -p ${DB_PORT}
    restart: always
    networks:
      - network

  admin:
    container_name: ${PROJECT_NAME}_admin
    image: dpage/pgadmin4
    ports:
      - "${ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    restart: always
    networks:
      - network
