version: "3.7"

networks:
  network:
    name: ${PROJECT_NAME}

services:
  front:
    container_name: ${PROJECT_NAME}_front
    image: nginx:stable-alpine
    ports:
      - ${FRONT_PORT}:80
    volumes:
      - ./docker/front:/var/www/html
      - ./docker/front/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - network

  engine:
    container_name: ${PROJECT_NAME}_engine
    image: php:7-fpm-alpine
    ports:
      - ${ENGINE_PORT}:9000
    volumes:
      - ./docker/front/html:/var/www/html
    restart: always
    networks:
      - network

  db:
    container_name: ${PROJECT_NAME}_db
    image: mariadb:latest
    ports:
      - ${DB_PORT}:3306
    # volumes:
    #   - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    networks:
      - network

  admin:
    container_name: ${PROJECT_NAME}_admin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${ADMIN_PORT}:80
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    networks:
      - network
